---
# file: roles/appserver/tasks/gunicorn.yml
#
# Creates {{ project_home }} owned by {{ webapp_group }}:{{ webapp_user }}
# Installs in it virtualenv, django, gunicorn. Also installs supervisor
# Syncs project mysite, hooks up gunicorn and supervisor with settings_production.py

- name: Install supervisor, virtualenv and python-dev, libpq-dev as required by pip
  apt: name={{ item }}
  with_items: 
    - supervisor
    - python-virtualenv
    - python-dev
    - libpq-dev

- name: Create webapps group
  group: name={{ webapp_group }} system=yes

- name: Create webapps user
  user: name={{ webapp_user }} group={{ webapp_group }} system=yes
    shell=/bin/bash home={{ webapp_home }}

- name: Add the ssh key
  authorized_key: user={{ webapp_user }} key="{{ lookup('file', 'authorized_keys') }}"

- name: Create the webapp project root directory
  sudo_user: "{{ webapp_user }}"
  file: path={{ project_home }} state=directory

- name: Create the virtualenv
  sudo_user: "{{ webapp_user }}"
  command: virtualenv {{ project_home }} 
    creates={{ project_home }}/bin/activate

- name: Install gunicorn
  sudo_user: "{{ webapp_user }}"
  pip: virtualenv={{ project_home }} name=gunicorn

- name: Install gunicorn start script
  sudo_user: "{{ webapp_user }}"
  template: src=gunicorn_start.sh dest={{ project_home }}/bin/ mode=0755

- name: Create directory for supervisor log
  sudo_user: "{{ webapp_user }}"
  file: path={{ project_home }}/logs state=directory

- name: Install supervisor start script
  template: src=gunicorn.conf dest=/etc/supervisor/conf.d/ mode=0755

- name: Add supervisor group
  supervisorctl: name=gunicorn state=present
