---
# file: roles/appserver/tasks/main.yml

- name: Install supervisor, virtualenv and python-dev, libpq-dev as required by pip
  apt: name={{item}}
  with_items: 
    - supervisor
    - python-virtualenv
    - python-dev
    - libpq-dev

- name: Create webapps group
  group: name={{ group }} system=yes

- name: Create webapps user
  user: name={{ user }} group={{ group }} system=yes shell=/bin/bash home=/webapps

- name: Add the ssh key
  authorized_key: user={{user}} key="{{ lookup('file', 'authorized_keys') }}"

- name: Create the django-tutorial webapp root directory
  sudo_user: "{{ user }}"
  file: path=/webapps/django-tutorial state=directory

- name: Create the virtualenv
  sudo_user: "{{ user }}"
  command: virtualenv /webapps/django-tutorial
    creates=/webapps/django-tutorial/bin/activate

- name: Install django, psycopg2 and gunicorn
  sudo_user: "{{ user }}"
  pip: virtualenv=/webapps/django-tutorial name={{item}}
  with_items:
    - django 
    - psycopg2
    - gunicorn
    - supervisor

- name: Copy the django project
  sudo: false
  remote_user: "{{ user }}"
  synchronize: src=../mysite dest=/webapps/django-tutorial/

- name: django sync database
  sudo_user: "{{ user }}"
  django_manage: command=syncdb app_path=/webapps/django-tutorial/mysite
    virtualenv=/webapps/django-tutorial

- name: Install gunicorn start script
  copy: src=gunicorn_start.sh dest=/webapps/django-tutorial/bin/ mode=0755
  sudo_user: "{{ user }}"

- name: Create log directory
  file: path=/webapps/django-tutorial/logs state=directory
  sudo_user: "{{ user }}"

- name: Install supervisor start script
  copy: src=gunicorn.conf dest=/etc/supervisor/conf.d/ mode=0755

- name: Add supervisor group
  supervisorctl: name=gunicorn state=present