---
# file: roles/appserver/tasks/main.yml
#
# Creates {{ project_home }} owned by {{ webapp_group }}:{{ webapp_user }}
# Installs in it virtualenv, django, gunicorn. Also installs supervisor
# Syncs project mysite, hooks up gunicorn and supervisor with settings_production.py

- name: Installs supervisor, virtualenv and python-dev, libpq-dev as required by pip
  apt: name={{ item }}
  with_items: 
    - python-virtualenv
    - python-dev
    - libpq-dev

- name: Create webapps group
  group: name={{ webapp_group }} system=yes

- name: Create webapps user
  user: name={{ webapp_user }} group={{ webapp_group }} system=yes
    shell=/bin/bash home={{ webapp_home }}

- name: Add the ssh key
  authorized_key: user={{ webapp_user }} key="{{ lookup('file', 'authorized_keys') }}"

- name: Create the webapp project root directory
  sudo_user: "{{ webapp_user }}"
  file: path={{ webapp.virtualenv }} state=directory

- name: Create the virtualenv
  sudo_user: "{{ webapp_user }}"
  command: virtualenv {{ webapp.virtualenv }} 
    creates={{ webapp.virtualenv }}/bin/activate

- name: Install django and psycopg2
  sudo_user: "{{ webapp_user }}"
  pip: virtualenv={{ webapp.virtualenv }} name={{item}}
  with_items:
    - django 
    - psycopg2

- name: trick me
  sudo: false
  remote_user: "{{ webapp_user }}"
  synchronize: src=../mysite/mysite dest={{ project_home }}/mysite recursive=no 
  changed_when: false

- name: Copy the django project
  sudo: false
  remote_user: "{{ webapp_user }}"
  synchronize: src=../mysite dest={{ project_home }}/ 
  # checksum=yes times=no

- name: Copy the production settings
  sudo_user: "{{ webapp_user }}"
  template: src=settings_production.py dest={{ project_home }}/mysite/mysite

- name: django migrate database
  sudo_user: "{{ webapp_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings_production
  django_manage: command=migrate app_path={{ project_home }}/mysite
    virtualenv={{ webapp.virtualenv }}

- template: src=dbbootstrap.json dest=/tmp

- name: django initial fixture
  sudo_user: "{{ webapp_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings_production
  django_manage: command="loaddata /tmp/dbbootstrap.json" app_path={{ project_home }}/mysite
    virtualenv={{ webapp.virtualenv }}

- include: "gunicorn.yml"
