---
# file: roles/webserver/tasks/main.yml

- name: Ensure nginx is installed
  apt: name=nginx

- name: Disable the default host
  file: path=/etc/nginx/sites-enabled/default state=absent
  register: ngconf1

- name: Copy the host configuration mysite
  copy: src=mysite dest=/etc/nginx/sites-available/
  register: ngconf2

- name: enable host mysite
  file: path=/etc/nginx/sites-enabled/mysite state=link src=../sites-available/mysite
  register: ngconf3

- name: restart ngingx
  service: name=nginx state=restarted
  when: ngconf1.changed or ngconf2.changed or ngconf3.changed
