---
# file: roles/local/tasks/main.yml
#
# Collects the static files

# Prerequisite: virtualenv and python-dev, libpq-dev which are required by pip
# OS X: pip install virtualenv; brew install postgresql
- apt: name={{ item }}
  with_items: 
    - python-virtualenv
    - python-dev
    - libpq-dev
  when: ansible_distribution == 'Ubuntu'

- name: Create the virtualenv
  command: virtualenv "{{ local.virtualenv }}"
    creates="{{ local.virtualenv }}/bin/activate"

- name: Install django, psycopg2 and gunicorn
  pip: virtualenv="{{ local.virtualenv }}" name={{ item }}
  with_items:
    - django 
    - psycopg2

- name: django sync static files
  django_manage: command=collectstatic app_path="{{ local.project_dir }}/mysite"
    virtualenv="{{ local.virtualenv }}"
