---
# file: roles/dbserver/tasks/main.yml
#
# Installs {{ postgresql_version }} connectable from {{ postgresql_intranet }}
# Creates {{ database }} with {{ dbuser }} and {{ dbpass }}


- name: Ensure postgresql is installed
  apt: name={{item}}
  with_items: 
    - postgresql-{{ postgresql_version }}
    - python-psycopg2

- name: Set postgresql to listen on 0.0.0.0/0
  sudo_user: postgres
  lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp='^listen_addresses = ' line="listen_addresses = '*'"
  register: pgconf1

- name: Allow access from the intranet
  sudo_user: postgres
  lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    line="host all all {{ postgresql_intranet }} md5" insertafter="EOF"
  register: pgconf2

- name: Restart
  service: name="postgresql" state="restarted"
  when: pgconf1.changed or pgconf2.changed

# $ sudo -u postgres createuser -D -A -P {{ dbuser }}
# $ sudo -u postgres createdb -O {{ dbuser }} {{ database }}

- name: Create database user
  sudo_user: postgres
  postgresql_user: name={{ dbuser }} password={{ dbpass }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE

- name: Create database
  sudo_user: postgres
  postgresql_db: name={{ database }} owner={{ dbuser }}
